-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

hl.env(
    "SSH_AUTH_SOCK",
    os.getenv("XDG_RUNTIME_DIR") .. "/gnupg/S.gpg-agent.ssh"
)

hl.env("LIBVA_DRIVER_NAME", "nvidia")          -- VA-API decode (libva-nvidia-driver)
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")  -- GLX vendor in XWayland

hl.env("XMODIFIERS", "@im=fcitx")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("https_proxy", "http://127.0.0.1:8889")
hl.env("no_proxy", "localhost,127.0.0.1,::1")

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		-- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
		kb_layout = "",
		numlock_by_default = true,
		follow_mouse = 0,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	-- gaps / border_size / rounding are managed by dms/layout.lua
	general = {
		layout = "dwindle",
	},
	decoration = {
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	-- Render XWayland at native 1:1 to avoid blur under fractional scaling (1.6).
	-- Tradeoff: XWayland windows are unscaled; compensate with in-app UI scaling.
	xwayland = {
		force_zero_scaling = true,
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		-- FPS cap for render_unfocused windows (games keep full fps in background)
		render_unfocused_fps = 60,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(nm-connection-editor|pavucontrol)$" }, float = true, center = true, size = { 900, 600 } })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true, center = true, size = { 600, 480 } })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
-- Steam notification toasts: float pinned at bottom-right, 20px margin
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)$" },
	no_initial_focus = true,
	pin = true
})
-- gamescope containers also keep full fps in background
hl.window_rule({
	match = { class = "^(gamescope)$" },
	render_unfocused = true,
})
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

-- Elden Ring Nightreign -> named workspace 
-- Use a normal named workspace so SUPER+1..9 can leave it normally.
hl.window_rule({
	match = { class = "^(steam_app_2622380|nightreign\\.exe)$" },
	workspace = "name: silent",
	render_unfocused = true,
})

hl.unbind("SUPER + G")
hl.bind("SUPER + G", function()
	local workspace = hl.get_active_workspace()
	local target = workspace and workspace.name == "" and "previous" or "name:"
	hl.dispatch(hl.dsp.focus({ workspace = target }))
end, { description = "Toggle game workspace" })
