-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "dms ipc call spotlight toggle" })
hl.unbind("SUPER + SHIFT + E")
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
hl.unbind("SUPER + SHIFT + Q")
hl.bind("SUPER + SHIFT + Q", hl.dsp.exec_cmd("dms ipc call notifications toggle"), { description = "dms ipc call notifications toggle" })
hl.unbind("SUPER + SHIFT + R")
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("dms ipc call workspace-rename open"), { description = "dms ipc call workspace-rename open" })
hl.unbind("SUPER + N")
hl.bind("SUPER + N", hl.dsp.focus({ workspace = "e+1" }), { description = "focus workspace e+1" })
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.focus({ workspace = "e-1" }), { description = "focus workspace e-1" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("sh -c \"sh -c \\\"emacsclient -c -a= -F '((height . 50) (width . 150))'\\\"\""))
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("~/.config/doom/scripts/dirvish"))
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("~/.config/doom/scripts/vterm"))
hl.unbind("ALT + Print")
hl.unbind("ALT + space")
hl.unbind("CTRL + Print")
hl.unbind("CTRL + SHIFT + R")
hl.unbind("SUPER + I")
hl.unbind("SUPER + TAB")
hl.unbind("SUPER + U")
hl.unbind("SUPER + X")
hl.unbind("SUPER + Y")
hl.unbind("SUPER + space")
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("dms ipc call defaultApp browser"), { description = "Default Web Browser: Open" })
